import { X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { evidenceApi } from '../api/client'
import { useAuth } from '../auth/useAuth'

const evidenceTypes = ['screenshot', 'log', 'error', 'text', 'trace']

export function CreateEvidenceDialog({ resultId, onClose, onCreated }) {
  const dialog = useRef(null); const { logout } = useAuth(); const [form, setForm] = useState({ type: 'text', name: '', description: '', content: '' }); const [pending, setPending] = useState(false); const [error, setError] = useState('')
  useEffect(() => { const previous = document.activeElement; const element = dialog.current; element?.showModal(); return () => { element?.close(); previous?.focus() } }, [])
  async function submit(event) { event.preventDefault(); if (!form.name.trim()) { setError('Enter an evidence name.'); return }; setPending(true); setError(''); try { const evidence = await evidenceApi.create(resultId, { type: form.type, name: form.name.trim(), description: form.description.trim() || null, content: form.content.trim() || null }); onCreated(evidence) } catch (requestError) { if (requestError.code === 'unauthorized') logout('Your session expired. Sign in again.'); else setError(requestError.message) } finally { setPending(false) } }
  return <dialog ref={dialog} className="project-dialog library-dialog verification-dialog" aria-labelledby="create-evidence-heading" onCancel={(event) => { event.preventDefault(); if (!pending) onClose() }}><header><div><p className="eyebrow">Verification record</p><h2 id="create-evidence-heading">Attach evidence</h2></div><button onClick={onClose} disabled={pending} aria-label="Close"><X /></button></header><form onSubmit={submit} noValidate>{error && <div className="form-alert" role="alert">{error}</div>}<div className="library-form-row"><div className="field"><label htmlFor="evidence-type">Type</label><select id="evidence-type" value={form.type} disabled={pending} onChange={(event) => setForm({ ...form, type: event.target.value })}>{evidenceTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select></div><div className="field"><label htmlFor="evidence-name">Name</label><input id="evidence-name" autoFocus maxLength="180" value={form.name} disabled={pending} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Console output" /></div></div><div className="field"><label htmlFor="evidence-description">Description <span>Optional</span></label><textarea id="evidence-description" rows="3" value={form.description} disabled={pending} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="What this evidence demonstrates" /></div><div className="field"><label htmlFor="evidence-content">Content or reference <span>Optional</span></label><textarea id="evidence-content" rows="6" value={form.content} disabled={pending} onChange={(event) => setForm({ ...form, content: event.target.value })} placeholder="Paste a log, trace, text, or a link to a stored screenshot." /></div><footer><button type="button" className="secondary-button" onClick={onClose} disabled={pending}>Cancel</button><button className="primary-button" disabled={pending}>{pending ? 'Attaching...' : 'Attach evidence'}</button></footer></form></dialog>
}
