import { FileSearch, LoaderCircle } from 'lucide-react'
import { useEffect, useState } from 'react'
import { evidenceApi, projectsApi, testSuitesApi, verificationRunsApi } from '../api/client'

export function EvidencePage() {
  const [projects, setProjects] = useState([]); const [projectId, setProjectId] = useState(''); const [items, setItems] = useState([]); const [status, setStatus] = useState('loading'); const [error, setError] = useState(''); const selectedProjectId = projectId || projects[0]?.id || ''
  useEffect(() => { projectsApi.list().then((data) => { setProjects(data); setStatus('ready') }).catch((err) => { setError(err.message); setStatus('error') }) }, [])
  useEffect(() => { if (!selectedProjectId) return; let active = true; (async () => { try { const suites = await testSuitesApi.list(selectedProjectId); const runSummaries = (await Promise.all(suites.map((suite) => verificationRunsApi.list(suite.id)))).flat(); const runs = await Promise.all(runSummaries.map((run) => verificationRunsApi.read(run.id))); const results = runs.flatMap((run) => run.results || []); const evidence = (await Promise.all(results.map(async (result) => (await evidenceApi.list(result.id)).map((entry) => ({ ...entry, runName: runs.find((run) => run.id === result.verification_run_id)?.name || 'Verification run' }))))).flat(); if (active) { setItems(evidence); setStatus('ready') } } catch (err) { if (active) { setError(err.message); setStatus('error') } } })(); return () => { active = false } }, [selectedProjectId])
  return <main className="library-page evidence-page"><section className="library-heading"><div><p className="eyebrow">Traceable verification record</p><h2>Evidence</h2><p>Evidence attached to verification results in the selected project.</p></div><label>Project<select value={selectedProjectId} onChange={(event) => { setStatus('loading'); setItems([]); setError(''); setProjectId(event.target.value) }} disabled={!projects.length}><option value="">Select a project</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label></section>{status === 'loading' && <div className="projects-state"><LoaderCircle className="spinner" /><p>Loading evidence...</p></div>}{status === 'error' && <div className="projects-state projects-state--error"><p>{error}</p></div>}{status === 'ready' && !selectedProjectId && <div className="projects-state"><FileSearch /><p>Create a project to begin collecting evidence.</p></div>}{status === 'ready' && selectedProjectId && !items.length && <div className="projects-state"><FileSearch /><p>No evidence has been attached in this project.</p></div>}{status === 'ready' && items.length > 0 && <section className="evidence-grid">{items.map((item) => <article className="evidence-card" key={item.id}><p className="eyebrow">{item.type} · {item.runName}</p><h3>{item.name}</h3>{item.description && <p>{item.description}</p>}{item.content && <pre>{item.content}</pre>}<small>Recorded {new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(item.created_at))}</small></article>)}</section>}</main>
}
