import { BarChart3, LoaderCircle } from 'lucide-react'
import { useEffect, useState } from 'react'
import { projectsApi, reportsApi } from '../api/client'

export function InsightsPage() {
  const [projects, setProjects] = useState([]); const [projectId, setProjectId] = useState(''); const [data, setData] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const selectedProjectId = projectId || projects[0]?.id || ''
  useEffect(() => { projectsApi.list().then((items) => { setProjects(items); setLoading(false) }).catch((err) => { setError(err.message); setLoading(false) }) }, [])
  useEffect(() => { if (!selectedProjectId) return; let active = true; Promise.all([reportsApi.project(selectedProjectId), reportsApi.trend(selectedProjectId), reportsApi.issues(selectedProjectId)]).then(([report, trend, issueReport]) => { if (active) setData({ report, trend, issueReport }) }).catch((err) => { if (active) setError(err.message) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [selectedProjectId])
  const metrics = data && [['Pass rate', `${data.report.tests.pass_rate}%`], ['Completed runs', data.report.verification.completed_runs], ['Open issues', data.issueReport.open], ['Failed tests', data.report.tests.failed]]
  return <main className="library-page insights-page"><section className="library-heading"><div><p className="eyebrow">Project reporting</p><h2>Insights</h2><p>Live verification and issue reports from your project record.</p></div><label>Project<select value={selectedProjectId} onChange={(event) => { setLoading(true); setData(null); setError(''); setProjectId(event.target.value) }}><option value="">Select a project</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label></section>{loading && <div className="projects-state"><LoaderCircle className="spinner" /><p>Loading reports...</p></div>}{error && !loading && <div className="projects-state projects-state--error"><p>{error}</p></div>}{!loading && !error && !selectedProjectId && <div className="projects-state"><BarChart3 /><p>Select a project to view its reports.</p></div>}{data && !loading && <><section className="runs-metrics">{metrics.map(([name, value]) => <article key={name}><span>{name}</span><strong>{value}</strong></article>)}</section><section className="access-grid"><article className="report-panel"><h3>Test outcomes</h3><ul className="simple-list">{Object.entries(data.report.tests).filter(([key]) => ['total', 'passed', 'failed', 'blocked', 'skipped', 'pending'].includes(key)).map(([key, value]) => <li key={key}><strong>{key.replace('_', ' ')}</strong><span>{value}</span></li>)}</ul></article><article className="report-panel"><h3>Issue breakdown</h3><ul className="simple-list">{Object.entries(data.issueReport.by_priority).map(([key, value]) => <li key={`priority-${key}`}><strong>{key} priority</strong><span>{value}</span></li>)}{Object.entries(data.issueReport.by_severity).map(([key, value]) => <li key={`severity-${key}`}><strong>{key} severity</strong><span>{value}</span></li>)}</ul></article></section><section className="report-panel"><h3>Verification trend</h3>{data.trend.length ? <div className="trend-list">{data.trend.map((point) => <div key={point.date}><strong>{point.date}</strong><span>{point.runs} runs · {point.passed} passed · {point.failed} failed · {point.blocked} blocked</span></div>)}</div> : <p>No completed verification activity is available yet.</p>}</section></>}</main>
}
