import { ArrowUpRight, CircleCheck, Cloud, FolderKanban, LoaderCircle, ShieldCheck, Waypoints } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { dashboardApi } from '../api/client'
import { useAuth } from '../auth/useAuth'

export function OverviewPage() {
  const { user } = useAuth(); const firstName = user?.full_name?.split(' ')[0] || 'there'; const [summary, setSummary] = useState(null); const [error, setError] = useState('')
  useEffect(() => { let active = true; dashboardApi.summary().then((data) => { if (active) setSummary(data) }).catch((requestError) => { if (active) setError(requestError.message) }); return () => { active = false } }, [])
  const workspaceReady = summary?.total_projects > 0
  return <main className="overview"><section className="overview-hero"><div><p className="eyebrow"><span className="live-dot" />Workspace ready</p><h2>Good to see you, {firstName}.</h2><p>{workspaceReady ? `${summary.total_projects} project${summary.total_projects === 1 ? '' : 's'} in your verification workspace.` : 'Your verification workspace is connected and ready for its first project.'}</p></div><div className="hero-gate" aria-hidden="true"><Waypoints /></div></section><section className="status-grid" aria-label="Workspace status"><article><div className="status-icon status-icon--green"><ShieldCheck /></div><div><p>Account status</p><strong>{user?.is_active ? 'Active' : 'Inactive'}</strong><small>Identity verified by API</small></div></article><article><div className="status-icon status-icon--cyan"><Cloud /></div><div><p>Verification health</p><strong>{summary ? `${summary.pass_rate}% pass rate` : 'Loading...'}</strong><small>{summary ? `${summary.total_verification_runs} total runs` : 'Loading live workspace data'}</small></div></article><article><div className="status-icon"><CircleCheck /></div><div><p>Open issues</p><strong>{summary?.open_issues ?? '—'}</strong><small>{summary ? `${summary.failed_results} failed results` : 'Live dashboard summary'}</small></div></article></section>{error && <div className="form-alert" role="alert">Dashboard data is unavailable: {error}</div>}{!summary && !error ? <div className="projects-state"><LoaderCircle className="spinner" /><p>Loading workspace summary...</p></div> : <section className="empty-workspace"><div className="empty-visual" aria-hidden="true"><FolderKanban /><span /><span /></div><div><p className="eyebrow">Your verification record</p><h3>{workspaceReady ? 'Continue verification work' : 'Build your project workspace'}</h3><p>{workspaceReady ? `${summary.total_test_suites} suites, ${summary.total_test_cases} test cases, and ${summary.total_verification_results} recorded results are available.` : 'Projects connect repositories, test suites, runs, evidence and issues into one traceable verification record.'}</p><Link className="workspace-action" to={workspaceReady ? '/app/runs' : '/app/projects'}>{workspaceReady ? 'View runs' : 'Manage projects'} <ArrowUpRight /></Link><small>{workspaceReady ? 'Review the latest execution record and evidence.' : 'Create and maintain projects in VeriGate.'}</small></div></section>}</main>
}
