import { CheckCircle2, FileCheck2, LoaderCircle, Pencil, Plus, Search, Trash2, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { projectsApi, testCasesApi, testSuitesApi } from '../api/client'
import { chooseProject, rememberProject } from '../testLibrary/projectSelection'
import { LibraryDialog } from './TestLibraryPage'

export function TestCasesPage() {
  const [projects, setProjects] = useState([]), [projectId, setProjectId] = useState('')
  const [suites, setSuites] = useState([]), [cases, setCases] = useState([])
  const [status, setStatus] = useState('loading'), [error, setError] = useState('')
  const [query, setQuery] = useState(''), [suiteFilter, setSuiteFilter] = useState('all'), [priority, setPriority] = useState('all')
  const [editing, setEditing] = useState(undefined)
  useEffect(() => { let active = true; projectsApi.list().then((items) => { if (!active) return; setProjects(items); setProjectId(chooseProject(items)); if (!items.length) setStatus('ready') }).catch((requestError) => { if (active) { setError(requestError.message); setStatus('error') } }); return () => { active = false } }, [])
  useEffect(() => { if (!projectId) return undefined; let active = true; testSuitesApi.list(projectId).then(async (items) => { const groups = await Promise.all(items.map(async (suite) => (await testCasesApi.list(suite.id)).map((testCase) => ({ ...testCase, suite_name: suite.name })))); if (active) { setSuites(items); setCases(groups.flat()); setStatus('ready') } }).catch((requestError) => { if (active) { setError(requestError.message); setStatus('error') } }); return () => { active = false } }, [projectId])
  function changeProject(id) { rememberProject(id); setProjectId(id); setSuites([]); setCases([]); setSuiteFilter('all'); setStatus('loading'); setError('') }
  const visibleCases = useMemo(() => cases.filter((testCase) => (suiteFilter === 'all' || testCase.test_suite_id === suiteFilter) && (priority === 'all' || testCase.priority === priority) && `${testCase.title} ${testCase.description || ''}`.toLowerCase().includes(query.toLowerCase())), [cases, priority, query, suiteFilter])
  function save(saved) { const suite = suites.find((item) => item.id === saved.test_suite_id); const enriched = { ...saved, suite_name: suite?.name || 'Unknown suite' }; setCases((current) => current.some((item) => item.id === saved.id) ? current.map((item) => item.id === saved.id ? enriched : item) : [enriched, ...current]); setEditing(undefined) }
  async function remove(testCase) { if (!window.confirm(`Delete “${testCase.title}”?`)) return; try { await testCasesApi.remove(testCase.id); setCases((current) => current.filter((item) => item.id !== testCase.id)) } catch (requestError) { setError(requestError.message) } }
  const createSuiteId = suiteFilter !== 'all' ? suiteFilter : suites[0]?.id
  return <main className="library-page cases-view"><section className="library-heading"><div><p className="eyebrow">Project-wide case registry</p><h2>Test Cases</h2><p>Search and manage cases across every suite in the selected project.</p></div>{projects.length > 0 && <label>Project<select value={projectId} onChange={(event) => changeProject(event.target.value)}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>}</section>
    {error && <div className="library-alert" role="alert"><span>{error}</span><button onClick={() => setError('')} aria-label="Dismiss error"><X /></button></div>}
    {status === 'loading' && <div className="projects-state"><LoaderCircle className="spinner" /><p>Loading test cases...</p></div>}
    {status === 'ready' && !projects.length && <section className="projects-empty"><div><FileCheck2 /></div><p className="eyebrow">Project required</p><h3>Create a project first</h3><p>Test cases are organized through project-owned suites.</p><Link className="library-link-button" to="/app/projects"><Plus />Create project</Link></section>}
    {status === 'ready' && projects.length > 0 && !suites.length && <section className="projects-empty"><div><FileCheck2 /></div><p className="eyebrow">Suite required</p><h3>Create a test suite first</h3><p>A test case must belong to a suite.</p><Link className="library-link-button" to="/app/test-suites"><Plus />Create suite</Link></section>}
    {status === 'ready' && suites.length > 0 && <><section className="case-filters"><label className="case-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search test cases" aria-label="Search test cases" /></label><select value={suiteFilter} onChange={(event) => setSuiteFilter(event.target.value)} aria-label="Filter by suite"><option value="all">All suites</option>{suites.map((suite) => <option key={suite.id} value={suite.id}>{suite.name}</option>)}</select><select value={priority} onChange={(event) => setPriority(event.target.value)} aria-label="Filter by priority"><option value="all">All priorities</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select><button className="new-project-button" onClick={() => setEditing(null)}><Plus />New test case</button></section><p className="result-count">Showing {visibleCases.length} of {cases.length} test cases</p>{!visibleCases.length ? <div className="case-empty filtered-empty"><FileCheck2 /><h4>{cases.length ? 'No matching test cases' : 'No test cases yet'}</h4><p>{cases.length ? 'Adjust the search or filters.' : 'Define the first executable case for this project.'}</p>{!cases.length && <button onClick={() => setEditing(null)}><Plus />Create test case</button>}</div> : <section className="all-cases-list">{visibleCases.map((testCase) => <article className={`case-card ${!testCase.is_active ? 'is-inactive' : ''}`} key={testCase.id}><div className="case-status"><CheckCircle2 /></div><div className="case-body"><div><span className={`priority priority--${testCase.priority}`}>{testCase.priority}</span><span className="case-activity">{testCase.suite_name} · {testCase.is_active ? 'Active' : 'Inactive'}</span></div><h4>{testCase.title}</h4><p>{testCase.description || 'No description provided.'}</p><details><summary>View execution definition</summary><div><strong>Steps</strong><pre>{testCase.steps}</pre><strong>Expected result</strong><p>{testCase.expected_result}</p></div></details></div><div className="case-actions"><button onClick={() => setEditing(testCase)} aria-label={`Edit ${testCase.title}`}><Pencil /></button><button className="danger-action" onClick={() => remove(testCase)} aria-label={`Delete ${testCase.title}`}><Trash2 /></button></div></article>)}</section>}</>}
    {editing !== undefined && <LibraryDialog kind="case" item={editing} parentId={editing?.test_suite_id || createSuiteId} parentOptions={editing ? [] : suites} onClose={() => setEditing(undefined)} onSaved={save} />}
  </main>
}
